# Configuration file for evaluating the adapters using LLM-as-judge    

fraction_of_data_examples_to_test: 1.0
checkpoint_path: ""
large_llm: "gpt-4o-mini" # The frontier model referred to as LLM in the manuscript.
num_runs: 5 # Number of times to run the evaluation
wanted_behaviors:
  - meeting 
  - expert_opinion
  - politics
adapter_mode: single #  single, merged

dataset_variation: "vary_all" # Options: "vary_all", "fixed_character", "fixed_history"
