# Hardcoded set of character names and traits.
# To reduce the time it takes to generate the datasets, and ensure that the names and traits are distinct, we pregenerate the fields that are used in the dataset generation.
# Can be extended to repeatedly generate new names and traits and prune duplicates until a sufficiently diverse set is found.

character_names = [
    "Aiden", "Bella", "Caleb", "Daisy", "Ethan", "Fiona", "Gavin", "Hannah", "Isaac", "Julia",
    "Kai", "Lily", "Mason", "Nora", "Oliver", "Penelope", "Quinn", "Ruby", "Sawyer", "Tessa", 
    "Ulysses", "Violet", "Wyatt", "Xena", "Yara", "Zoe", "Asher", "Chloe", "Declan", "Emma",
    "Finn", "Grace", "Harper", "Ivy", "Jack", "Kylie", "Liam", "Mia", "Noah", "Olivia",
    "Piper", "Ryder", "Sophia", "Theo", "Uma", "Vincent", "Willow", "Xavier", "Yasmin", "Zack",
    "Ava", "Benjamin", "Claire", "Daniel", "Ella", "Felix", "Gemma", "Henry", "Isabella", "James",
    "Kate", "Leo", "Mila", "Nathan", "Oscar", "Poppy", "Quincy", "Riley", "Sadie", "Tyler",
    "Ursula", "Vera", "William", "Xiomara", "Yuki", "Zachary", "Abigail", "Blake", "Cora", "Dylan",
    "Evelyn", "Freya", "Grayson", "Hazel", "Ian", "Jasmine", "Knox", "Luna", "Miles", "Nova",
    "Owen", "Paige", "Rowan", "Scarlett", "Toby", "Unity", "Valentina", "Wesley", "Xander", "Zara",
    "Adrian", "Bianca", "Camden", "Diana", "Eden", "Flynn", "Georgia", "Hugo", "Iris", "Jude",
    "Keira", "Lucas", "Maya", "Nash", "Orion", "Pearl", "Rafael", "Sage", "Thea", "Urban",
    "Victoria", "Wade", "Ximena", "Yael", "Zander", "Alice", "Bryce", "Celeste", "Dean", "Elise",
    "Francis", "Gwen", "Heath", "Indie", "Jonas", "Kaia", "Lance", "Maeve", "Nico", "Odette",
    "Phoenix", "River", "Roman", "Sierra", "Tristan", "Uriah", "Valen", "Winter", "Xiomar", "Yuna",
    "Zephyr", "Aria", "Beau", "Carmen", "Dante", "Echo", "Forest", "Gloria", "Hayes", "Ingrid", "Joel",
    "Kira", "Luca", "Marina", "Nolan", "Opal", "Paris", "Quest", "Rhys", "Selena", "Tate",
    "Umberto", "Vivian", "Wren", "Xerxes", "Yves", "Zelda", "August", "Blair", "Cole", "Dawn",
    "Ellis", "Flora", "Grant", "Hope", "Indigo", "Jane", "Leah", "Marco", "Nina",
    "Otto", "Petra", "Quill", "Reed", "Skye", "Troy", "Upton", "Vale", "Wynn", "Xavi", "York", "Zeus",
    "Atlas", "Bridget", "Cyrus", "Dahlia", "Ezra", "Farrah", "Griffin", "Harmony", "Ignatius", "Jade",
    "Kieran", "Lyra", "Magnus", "Naomi", "Osiris", "Phoebe", "Quartz", "Raven", "Sterling", "Terra",
    "Ulrich", "Vesper", "Wilder", "Xiara", "Yannick", "Zinnia", "Ash", "Beatrix", "Cassius", "Daphne",
    "Ember", "Falcon", "Genesis", "Holden", "Isolde", "Jericho", "Kestrel", "Lennon", "Marlowe", "Neptune",
    "Onyx", "Perseus", "Quentin", "Remy", "Soren", "Tempest", "Umber", "Vega", "Wolf", "Xanthe",
    "Acacia", "Bastian", "Cassian", "Darius", "Elowen", "Fleur", "Galatea", "Helios", "Io", "Juniper",
    "Kairos", "Larkin", "Meridian", "Nerissa", "Octavia", "Peregrine", "Quinlan", "Rosario", "Sylvan", "Thaddeus",
    "Undine", "Valkyrie", "Wraith", "Xenon", "Yarrow", "Zephyrine", "Altair", "Bellamy", "Caspian", "Dorian",
    "Endora", "Fable", "Galahad", "Halcyon", "Icarus", "Jovian", "Kalliope", "Lysander", "Morpheus", "Nephele",
    "Oberon", "Pandora", "Quintessa", "Raziel", "Saphira", "Thanatos", "Urania", "Vespera", "Wisteria", "Xerces",
    "Yggdrasil", "Zenith", "Arcturus", "Belladonna", "Calypso", "Demetrius", "Eulalia", "Fenris", "Galadriel", "Hyperion",
    "Ianthe", "Jessamine", "Korinth", "Leander", "Malachite", "Nymeria", "Orpheus", "Persephone", "Quillan", "Reverie",
    "Seraphim", "Thorne", "Umbra", "Viatrix", "Wolfram", "Xanthus", "Yvaine", "Zillah", "Alaric", "Bryony",
    "Cassiopeia", "Draven", "Elodie", "Faelan", "Gwyneira", "Helicon", "Illyria", "Jareth", "Kylian", "Lorelei",
    "Melisande", "Novalis", "Oleander", "Pyralis", "Quintilian", "Ravenna", "Syrinx", "Thalassa", "Uilani", "Viridian",
    "Wrenna", "Xylon", "Ysabeau", "Zarina", 
    "Amara", "Beckett", "Cressida", "Dominic", "Elara", "Finnian", "Genevieve", "Harlow", "Isidore", "Jessalyn",
    "Killian", "Lucinda", "Matteo", "Nyx", "Orson", "Primrose", "Quillon", "Rhiannon", "Silas", "Tabitha",
    "Vivienne", "Weston", "Yorick", "Zahara", "Atticus", "Briar", "Calix", "Delphine",
    "Evander", "Faye", "Gideon", "Harley", "Kenna", "Leif", "Maren", "Nikolai",
    "Ophelia", "Prosper", "Ronan", "Serenity", "Tavish", "Uriel", "Verity", "Whitley",
    "Adira", "Bram", "Cosima", "Dax", "Elysia", "Fergus", "Giselle", "Huxley",
    "Imogen", "Jagger", "Linden", "Marisol", "Niles", "Pax", "Rosalind",
    "Thalia", "Ulani", "Vaughn", "Waverly", "Amina", "Bodhi",
    "Cleo", "Darian", "Eleni", "Finch", "Galen", "Hadley", "Idris", "Jubilee", "Keir", "Linnea",
    "Micah", "Nadia", "Orla", "Phineas", "Quintin", "Ramona", "Stellan", "Tatum", "Ursa",
    "Winona", "Xio", "Zeke", "Amalia", "Brecken", "Calista", "Deveraux", "Eloisa", "Finian",
    "Gianna", "Hendrix", "Isadora", "Jace", "Koa", "Lark", "Milo", "Noor", "Orrin", "Paloma",
    "Quade", "Raina", "Saylor", "Tegan", "Veda", "Wiley", "Zane",
    "Annika", "Bowen", "Calla", "Dashiell", "Elspeth", "Finley", "Greer", "Ione", "Jorah",
    "Kian", "Leilani", "Maddox", "Nessa", "Ozias", "Poet", "Quinby", "Rune", "Sutton", "Talia",
    "Ula", "Willa", "Zora", "Astra", "Boden", "Ciel", "Diem",
    "Eira", "Fern", "Gaia", "Hester", "Indra", "Juno", "Kace", "Lumen", "Maris", "Nuri",
    "Oren", "Quimby", "Sol", "Xyla", "Zuri", "Auden", "Brynn", "Caius", "Dara", "Elio", 
    "Greta", "Ivo", "Jora", "Lev", "Mina", "Neo", "Oona", "Shai", "Zev", 
    "Alden", "Bronte", "Cedric", "Darcy", "Esme", "Flint", "Geneva", "Hollis", "Ira", "Jolie",
    "Kade", "Lavinia", "Merritt", "Niamh", "Orville", "Priya", "Quinnell", "Romilly", "Shiloh", "Tamsin",
    "Udo", "Vanya", "Walden", "Xara", "Yanni", "Alistair", "Beryl", "Callum", "Delia",
    "Eamon", "Frida", "Gareth", "Honora", "Inez", "Jethro", "Lucian", "Margot", "Niall",
    "Ottilie", "Pascal", "Questa", "Rafferty", "Simone", "Thayer", "Ulla", "Virgil", "Winifred", "Xenia",
    "Arlo", "Beatrice", "Cormac", "Drusilla", "Emrys", "Fionnula", "Giles", "Hermione",
    "Ignacio", "Jocelyn", "Keaton", "Liora", "Marius", "Nola", "Oswald", "Philomena", "Quigley", "Rowena",
    "Severin", "Tamara", "Ultan", "Viveca", "Wallis", "Xanthia", "Yolanda", "Zeno", "Alastair", "Brynja",
    "Caelan", "Delilah", "Freja", "Garland", "Helene", "Ishmael", "Jessamy", "Kamal", "Livia",
    "Malachi", "Nerida", "Osias", "Philipa", "Quirin", "Rosemary", "Saffron", "Ulyana", "Vittorio",
    "Wilhelmina", "Xaviera", "Zephyra", "Ansel", "Bernadette", "Cillian", "Dorothea", "Edmund", "Fionnuala",
    "Gawain", "Henrietta", "Jacinda", "Kendrick", "Lucretia", "Matthias", "Nerys", "Osmond", "Philippa",
    "Quinton", "Rosalba", "Seraphina", "Thelonius", "Ulyssa", "Vincenzo", "Yasmine", "Zeferino"
]

character_traits = [
    "Curious, Analytical, Patient",
    "Energetic, Creative, Optimistic",
    "Calm, Empathetic, Wise",
    "Ambitious, Confident, Charismatic",
    "Introverted, Thoughtful, Artistic",
    "Adventurous, Spontaneous, Humorous",
    "Logical, Precise, Organized",
    "Compassionate, Nurturing, Intuitive",
    "Determined, Resilient, Focused",
    "Playful, Imaginative, Carefree",
    "Diplomatic, Tactful, Perceptive",
    "Practical, Reliable, Hardworking",
    "Enthusiastic, Sociable, Outgoing",
    "Reserved, Observant, Analytical",
    "Innovative, Visionary, Risk-taking",
    "Gentle, Patient, Understanding",
    "Assertive, Direct, Honest",
    "Adaptable, Flexible, Open-minded",
    "Disciplined, Methodical, Persistent",
    "Empathetic, Supportive, Encouraging",
    "Curious, Supportive, Intellectual",
    "Passionate, Intense, Driven",
    "Calm, Composed, Levelheaded",
    "Cheerful, Upbeat, Positive",
    "Reflective, Introspective, Philosophical",
    "Efficient, Productive, Goal-oriented",
    "Imaginative, Creative, Innovative",
    "Loyal, Dependable, Trustworthy",
    "Adventurous, Daring, Courageous",
    "Analytical, Driven, Rational",
    "Empathetic, Compassionate, Caring",
    "Ambitious, Driven, Determined",
    "Easygoing, Relaxed, Laid-back",
    "Charismatic, Charming, Persuasive",
    "Diligent, Hardworking, Industrious",
    "Intuitive, Perceptive, Insightful",
    "Optimistic, Hopeful, Positive",
    "Pragmatic, Practical, Realistic",
    "Curious, Inquisitive, Eager to learn",
    "Assertive, Confident, Self-assured",
    "Patient, Understanding, Tolerant",
    "Energetic, Lively, Enthusiastic",
    "Thoughtful, Considerate, Mindful",
    "Adaptable, Versatile, Flexible",
    "Organized, Systematic, Structured",
    "Creative, Imaginative, Inventive",
    "Reliable, Dependable, Consistent",
    "Ambitious, Goal-oriented, Driven",
    "Empathetic, Compassionate, Sympathetic",
    "Analytical, Critical thinker, Logical",
    "Cheerful, Joyful, Upbeat",
    "Calm, Serene, Tranquil",
    "Determined, Persistent, Tenacious",
    "Friendly, Sociable, Outgoing",
    "Innovative, Forward-thinking, Progressive",
    "Modest, Humble, Unassuming",
    "Passionate, Enthusiastic, Zealous",
    "Quirky, Eccentric, Unique",
    "Rational, Reasonable, Sensible",
    "Sincere, Genuine, Authentic",
    "Tactful, Diplomatic, Polite",
    "Unconventional, Non-conformist, Original",
    "Vigilant, Attentive, Observant",
    "Witty, Clever, Quick-thinking",
    "Youthful, Spirited, Vibrant",
    "Zealous, Fervent, Ardent",
    "Articulate, Eloquent, Well-spoken",
    "Benevolent, Generous, Altruistic",
    "Candid, Frank, Straightforward",
    "Daring, Bold, Audacious",
    "Efficient, Productive, Competent",
    "Farsighted, Visionary, Prescient",
    "Gregarious, Convivial, Affable",
    "Harmonious, Balanced, Peaceful",
    "Idealistic, Principled, Ethical",
    "Judicious, Discerning, Prudent",
    "Kindhearted, Benign, Gentle",
    "Luminous, Radiant, Effervescent",
    "Magnanimous, Generous, Forgiving",
    "Noble, Honorable, Dignified",
    "Persevering, Steadfast, Unwavering",
    "Quixotic, Idealistic, Romantic",
    "Refined, Cultured, Sophisticated",
    "Sagacious, Wise, Perceptive",
    "Tenacious, Resolute, Determined",
    "Unflappable, Composed, Collected",
    "Versatile, Adaptable, Multifaceted",
    "Whimsical, Fanciful, Playful",
    "Xenial, Hospitable, Welcoming",
    "Yearning, Aspiring, Ambitious",
    "Zestful, Enthusiastic, Eager",
    "Astute, Shrewd, Perspicacious",
    "Benevolent, Philanthropic, Charitable",
    "Cogent, Convincing, Compelling",
    "Dauntless, Intrepid, Fearless",
    "Erudite, Scholarly, Learned",
    "Fastidious, Meticulous, Precise",
    "Methodical, Strategic, Forward-thinking",
    "Expressive, Dramatic, Passionate",
    "Stoic, Reserved, Contemplative",
    "Dynamic, Energetic, Motivating",
    "Meticulous, Detail-oriented, Thorough",
    "Spontaneous, Free-spirited, Uninhibited",
    "Diplomatic, Mediating, Harmonious",
    "Resourceful, Inventive, Adaptable",
    "Nurturing, Protective, Supportive",
    "Analytical, Systematic, Precise",
    "Charismatic, Magnetic, Influential",
    "Mindful, Present, Grounded",
    "Pioneering, Innovative, Groundbreaking",
    "Serene, Peaceful, Balanced",
    "Determined, Focused, Goal-driven",
    "Authentic, Genuine, Transparent",
    "Collaborative, Team-oriented, Cooperative",
    "Independent, Self-reliant, Autonomous",
    "Articulate, Communicative, Expressive",
    "Disciplined, Structured, Organized",
    "Intuitive, Instinctive, Perceptive",
    "Adventurous, Explorative, Bold",
    "Grounded, Matter-of-fact, Sensible",
    "Resilient, Adaptable, Tough",
    "Empowering, Encouraging, Uplifting",
    "Analytical, Data-driven, Objective",
    "Visionary, Future-oriented, Inspiring",
    "Humble, Modest, Flexible",
    "Decisive, Resolute, Clear-minded",
    "Observant, Attentive, Watchful",
    "Enthusiastic, Spirited, Animated",
    "Orderly, Efficient, Coordinated",
    "Innovative, Progressive, Revolutionary",
    "Balanced, Centered, Harmonious",
    "Proactive, Initiative-taking, Self-starting",
    "Reflective, Thoughtful, Contemplative",
    "Dynamic, Vigorous, Energetic",
    "Steadfast, Reliable, Constant",
    "Perceptive, Discerning, Astute",
    "Fearless, Undaunted, Adventuresome",
    "Systematic, Thorough, Rigorous",
    "Tactical, Measured, Strategic",
    "Expressive, Demonstrative, Emotional",
    "Focused, Concentrated, Attentive",
    "Adaptable, Adjustable, Flexible",
    "Resourceful, Ingenious, Clever",
    "Diplomatic, Tactful, Discreet",
    "Groundbreaking, Ingenious, Novel",
    "Patient, Tolerant, Understanding",
    "Unwavering, Relentless, Dogged",
    "Analytical, Investigative, Probing",
    "Charismatic, Engaging, Captivating",
    "Mindful, Aware, Conscious",
    "Pioneering, Trailblazing, Leading",
    "Serene, Calm, Collected",
    "Authentic, Real, Sincere",
    "Collaborative, Cooperative, United",
    "Independent, Autonomous, Self-directed",
    "Articulate, Fluent, Clear",
    "Disciplined, Self-controlled, Restrained",
    "Intuitive, Knowing, Sensing",
    "Adventurous, Venturesome, Enterprising",
    "Down-to-earth, Levelheaded, Pragmatic",
    "Creative, Inventive, Resourceful",
    "Resilient, Hardy, Tenacious",
    "Empowering, Strengthening, Enabling",
    "Analytical, Reasoning, Logical",
    "Visionary, Imaginative, Idealistic",
    "Decisive, Determined, Firm",
    "Observant, Perceptive, Sharp",
    "Enthusiastic, Eager, Keen",
    "Methodical, Organized, Systematic",
    "Innovative, Inventive, Creative",
    "Balanced, Stable, Steady",
    "Proactive, Anticipatory, Forward-thinking",
    "Reflective, Meditative, Introspective",
    "Dynamic, Active, Lively",
    "Steadfast, Unwavering, Faithful",
    "Perceptive, Aware, Observant",
    "Adventurous, Courageous, Intrepid",
    "Structured, Planned, Ordered",
    "Empathetic, Sensitive, Responsive",
    "Strategic, Planned, Deliberate",
    "Expressive, Communicative, Open",
    "Focused, Dedicated, Committed",
    "Adaptable, Versatile, Resilient",
    "Resourceful, Capable, Competent",
    "Diplomatic, Conciliatory, Peacekeeping",
    "Innovative, Pioneering, Groundbreaking",
    "Patient, Steady, Enduring",
    "Determined, Steadfast, Persistent",
    "Analytical, Methodical, Thorough",
    "Charismatic, Appealing, Attractive",
    "Mindful, Considerate, Thoughtful",
    "Pioneering, Enterprising, Initiating",
    "Serene, Tranquil, Placid",
    "Authentic, Trustworthy, Reliable",
    "Collaborative, Synergistic, Unified",
    "Independent, Self-sufficient, Capable",
    "Articulate, Coherent, Lucid",
    "Disciplined, Regulated, Controlled",
    "Mystical, Spiritual, Enlightened",
    "Rebellious, Defiant, Independent-minded",
    "Graceful, Elegant, Poised",
    "Fierce, Intense, Powerful",
    "Mischievous, Playful, Impish",
    "Yearning, Aspiring, Striving",
    "Zesty, Flavorful, Piquant", 
    "Pragmatic, Realistic, Grounded",
    "Whimsical, Dreamy, Imaginative",
    "Vibrant, Lively, Animated",
    "Stoic, Composed, Unruffled",
    "Daring, Brave, Fearless",
    "Exuberant, Bubbly, Effervescent",
    "Gentle, Tender, Mild",
    "Resolute, Determined, Unwavering",
    "Vivacious, Spirited, Energetic",
    "Diligent, Assiduous, Industrious",
    "Astute, Perceptive, Discerning",
    "Benign, Kind, Gentle",
    "Deft, Skillful, Adroit",
    "Earnest, Sincere, Heartfelt",
    "Fervent, Passionate, Ardent",
    "Gallant, Chivalrous, Noble",
    "Ingenious, Clever, Inventive",
    "Judicious, Prudent, Sensible",
    "Keen, Sharp, Acute",
    "Nimble, Agile, Quick",
    "Observant, Watchful, Vigilant",
    "Pensive, Contemplative, Meditative",
    "Quizzical, Questioning, Curious",
    "Resolute, Firm, Determined",
    "Sagacious, Wise, Insightful",
    "Urbane, Sophisticated, Polished",
    "Valiant, Courageous, Brave",
    "Winsome, Charming, Engaging",
    "Yielding, Compliant, Acquiescent",
    "Affable, Friendly, Amiable",
    "Buoyant, Cheerful, Optimistic",
    "Dauntless, Fearless, Intrepid",
    "Ebullient, Exuberant, Enthusiastic",
    "Felicitous, Apt, Appropriate",
    "Genial, Cordial, Congenial",
    "Halcyon, Peaceful, Tranquil",
    "Indefatigable, Tireless, Untiring",
    "Jocund, Cheerful, Merry",
    "Lissome, Graceful, Limber",
    "Mellifluous, Smooth, Melodious",
    "Nonchalant, Casual, Relaxed",
    "Opulent, Luxurious, Sumptuous",
    "Perspicacious, Discerning, Astute",
    "Quiescent, Still, Quiet",
    "Redoubtable, Formidable, Imposing",
    "Sanguine, Optimistic, Positive",
    "Taciturn, Reserved, Quiet",
    "Ubiquitous, Omnipresent, Pervasive",
    "Vociferous, Outspoken, Vocal",
    "Wily, Crafty, Cunning",
    "Yare, Nimble, Agile",
    "Zany, Comical, Silly", 
    "Blithe, Carefree, Lighthearted",
    "Circumspect, Cautious, Wary",
    "Doughty, Brave, Valiant",
    "Effulgent, Radiant, Brilliant",
    "Fulsome, Abundant, Copious",
    "Garrulous, Talkative, Chatty",
    "Heuristic, Investigative, Exploratory",
    "Ineffable, Indescribable, Unspeakable",
    "Jubilant, Joyful, Exultant",
    "Knavish, Mischievous, Roguish",
    "Loquacious, Talkative, Verbose",
    "Munificent, Generous, Bountiful",
    "Numinous, Spiritual, Transcendent",
    "Obdurate, Stubborn, Unyielding",
    "Pellucid, Clear, Transparent",
    "Recondite, Obscure, Abstruse",
    "Salubrious, Healthy, Wholesome",
    "Trenchant, Incisive, Cutting",
    "Uxorious, Devoted, Doting",
    "Verdant, Green, Lush",
    "Waggish, Playful, Mischievous",
    "Xenogenic, Foreign, External",
    "Yeomanly, Diligent, Hardworking",
    "Zestful, Enthusiastic, Hearty", 
    "Bibulous, Fond of drinking, Convivial",
    "Captious, Critical, Fault-finding",
    "Dilatory, Slow, Tardy",
    "Efficacious, Effective, Productive",
    "Fecund, Fertile, Productive",
    "Grandiloquent, Pompous, Bombastic",
    "Histrionic, Dramatic, Theatrical",
    "Iconoclastic, Rebellious, Unconventional",
    "Jocular, Humorous, Playful",
    "Kleptomaniac, Compulsive, Stealing",
    "Laconic, Brief, Concise",
    "Mawkish, Sentimental, Emotional",
    "Nefarious, Wicked, Villainous",
    "Obstreperous, Noisy, Unruly",
    "Parsimonious, Frugal, Stingy",
    "Quixotic, Idealistic, Impractical",
    "Recalcitrant, Defiant, Resistant",
    "Sycophantic, Flattering, Fawning",
    "Truculent, Aggressive, Belligerent",
    "Voluble, Talkative, Fluent",
    "Acerbic, Sharp, Biting",
    "Bellicose, Aggressive, Combative",
    "Capricious, Fickle, Unpredictable",
    "Deleterious, Harmful, Injurious",
    "Facetious, Humorous, Joking",
    "Garrulous, Talkative, Wordy",
    "Hedonistic, Pleasure-seeking, Self-indulgent",
    "Imperious, Domineering, Commanding",
    "Jejune, Naive, Simplistic",
    "Knavish, Dishonest, Unscrupulous",
    "Lascivious, Lustful, Lewd",
    "Mendacious, Dishonest, Lying",
    "Noxious, Harmful, Poisonous",
    "Obsequious, Servile, Fawning",
    "Perfidious, Treacherous, Disloyal",
    "Rambunctious, Boisterous, Unruly",
    "Salacious, Lustful, Indecent",
    "Turgid, Swollen, Bombastic",
    "Unctuous, Oily, Insincere",
    "Vacuous, Empty, Mindless",
    "Wanton, Undisciplined, Unrestrained",
    "Affable, Friendly, Pleasant",
    "Kind-hearted, Benevolent, Compassionate",
    "Lively, Energetic, Animated",
    "Perseverant, Persistent, Steadfast",
    "Resilient, Tough, Adaptable",
    "Valiant, Brave, Courageous",
    "Wise, Sage, Judicious", 
    "Dedicated, Committed, Devoted",
    "Eloquent, Articulate, Expressive",
    "Genuine, Authentic, Sincere",
    "Honorable, Upright, Principled",
    "Knowledgeable, Informed, Educated",
    "Loyal, Faithful, Devoted",
    "Quiet, Reserved, Calm",
    "Reliable, Dependable, Trustworthy",
    "Sincere, Genuine, Honest",
    "Unique, Distinctive, Original",
    "Versatile, Adaptable, Flexible",
    "Warm, Affectionate, Caring",
    "Xenodochial, Friendly to strangers, Hospitable",
    "Yearning, Longing, Aspiring",
    "Zestful, Enthusiastic, Energetic",
    "Bold, Daring, Fearless",
    "Compassionate, Empathetic, Kind",
    "Gracious, Courteous, Polite",
    "Helpful, Supportive, Beneficial",
    "Just, Fair, Equitable",
    "Kind, Gentle, Benevolent",
    "Loving, Affectionate, Caring",
    "Neat, Tidy, Orderly",
    "Open-minded, Receptive, Tolerant",
    "Peaceful, Calm, Serene",
    "Respectful, Courteous, Considerate",
    "Vigilant, Watchful, Alert",
    "Witty, Clever, Humorous",
    "Yielding, Compliant, Flexible",
    "Cerebral, Intellectual, Thoughtful",
    "Dignified, Stately, Majestic",
    "Enigmatic, Mysterious, Cryptic",
    "Formidable, Impressive, Powerful",
    "Guileless, Innocent, Artless",
    "Hermetic, Reclusive, Secluded",
    "Incisive, Penetrating, Sharp",
    "Jovial, Merry, Cheerful",
    "Kinetic, Lively, Dynamic",
    "Laconic, Terse, Concise",
    "Mercurial, Volatile, Changeable",
    "Nuanced, Subtle, Delicate",
    "Opinionated, Dogmatic, Assertive",
    "Puckish, Impish, Mischievous",
    "Quaint, Charming, Old-fashioned",
    "Reticent, Reserved, Restrained",
    "Stoic, Impassive, Unemotional",
    "Temperate, Moderate, Restrained",
    "Unassuming, Modest, Humble",
    "Venturesome, Daring, Adventurous",
    "Wistful, Yearning, Longing",
    "Xenophilic, Attracted to foreign cultures, Cosmopolitan",
    "Youthful, Fresh, Vigorous",
    "Zesty, Spicy, Lively",
    # Adding more unique traits to reach 500
    "Abrasive, Rough, Harsh",
    "Abstemious, Moderate, Temperate",
    "Accessible, Approachable, Available",
    "Accommodating, Obliging, Amenable",
    "Accomplished, Skilled, Proficient",
    "Accountable, Responsible, Answerable",
    "Accurate, Precise, Exact",
    "Acquisitive, Materialistic, Possessive",
    "Adamant, Unyielding, Inflexible",
    "Adept, Proficient, Skilled",
    "Adroit, Skillful, Dexterous",
    "Adumbrative, Foreshadowing, Prefiguring",
    "Adust, Scorched, Parched",
    "Advenient, Approaching, Coming",
    "Adventitious, Accidental, Fortuitous",
    "Adversarial, Opposing, Antagonistic",
    "Aesthetic, Artistic, Tasteful",
    "Affectionate, Loving, Tender",
    "Agile, Nimble, Dexterous",
    "Agnostic, Skeptical, Questioning",
    "Agreeable, Pleasant, Amiable",
    "Alacritous, Eager, Ready",
    "Alchemical, Transformative, Magical",
    "Alert, Watchful, Vigilant",
    "Aloof, Distant, Reserved",
    "Altruistic, Selfless, Giving",
    "Amatory, Loving, Amorous",
    "Ambidextrous, Versatile, Adaptable",
    "Ambivalent, Conflicted, Uncertain",
    "Ameliorative, Improving, Bettering",
    "Amenable, Agreeable, Compliant",
    "Amiable, Friendly, Sociable",
    "Amicable, Friendly, Peaceable",
    "Amorphous, Shapeless, Undefined",
    "Amphibious, Adaptable, Versatile",
    "Anachronistic, Outdated, Misplaced",
    "Analogical, Comparative, Parallel",
    "Anarchic, Chaotic, Lawless",
    "Anecdotal, Narrative, Story-based",
    "Angelic, Pure, Virtuous",
    "Angular, Sharp, Pointed",
    "Animated, Lively, Energetic",
    "Anomalous, Irregular, Abnormal",
    "Antediluvian, Ancient, Prehistoric",
    "Anthropomorphic, Human-like, Personified",
    "Anticipatory, Expectant, Forward-looking",
    "Antipathetic, Averse, Opposed",
    "Antiquated, Outdated, Old-fashioned",
    "Antithetical, Opposite, Contrary",
    "Anxious, Worried, Concerned",
    "Apathetic, Indifferent, Uninterested",
    "Aphoristic, Concise, Pithy",
    "Apocalyptic, Catastrophic, Cataclysmic",
    "Apologetic, Regretful, Contrite",
    "Apostolic, Missionary, Evangelical",
    "Apprehensive, Fearful, Anxious",
    "Approachable, Accessible, Friendly",
    "Appropriate, Suitable, Fitting",
    "Aquatic, Water-loving, Marine",
    "Arbitrary, Random, Capricious",
    "Arcadian, Rural, Pastoral",
    "Archetypal, Prototypical, Exemplary",
    "Ardent, Passionate, Fervent",
    "Arduous, Difficult, Strenuous",
    "Argute, Shrewd, Clever",
    "Aristocratic, Noble, Patrician",
    "Aromatic, Fragrant, Scented",
    "Arrogant, Haughty, Conceited",
    "Artful, Crafty, Cunning",
    "Articulate, Well-spoken, Eloquent",
    "Artificial, Synthetic, Man-made",
    "Artistic, Creative, Aesthetic",
    "Ascetic, Austere, Self-disciplined",
    "Asinine, Foolish, Silly",
    "Aspiring, Ambitious, Hopeful", 
    "Assiduous, Diligent, Persistent",
    "Assumptive, Presumptuous, Taking for granted",
    "Assured, Confident, Certain",
    "Astonishing, Amazing, Surprising",
    "Astringent, Harsh, Severe",
    "Astute, Shrewd, Perceptive",
    "Athletic, Sporty, Physically active",
    "Atrocious, Terrible, Dreadful",
    "Attentive, Observant, Mindful",
    "Attractive, Appealing, Alluring",
    "Audacious, Bold, Daring",
    "Augmentative, Increasing, Enhancing",
    "Auspicious, Favorable, Promising",
    "Austere, Severe, Stern",
    "Authoritarian, Dictatorial, Controlling",
    "Authoritative, Commanding, Influential",
    "Autocratic, Dictatorial, Domineering",
    "Autonomous, Independent, Self-governing",
    "Avaricious, Greedy, Covetous",
    "Averse, Opposed, Reluctant",
    "Avid, Eager, Enthusiastic",
    "Aweless, Fearless, Undaunted",
    "Awesome, Impressive, Remarkable",
    "Awful, Terrible, Dreadful",
    "Awkward, Clumsy, Ungainly",
    "Axiomatic, Self-evident, Obvious",
    "Babbling, Chattering, Prattling",
    "Bacchanalian, Festive, Riotous",
    "Baleful, Harmful, Menacing",
    "Ballistic, Explosive, Uncontrolled",
    "Banal, Trite, Commonplace",
    "Barbaric, Savage, Primitive",
    "Barbarous, Cruel, Brutal",
    "Barbed, Sharp, Pointed",
    "Baronial, Lordly, Magnificent",
    "Baroque, Ornate, Elaborate",
    "Barren, Sterile, Unproductive",
    "Bashful, Shy, Timid",
    "Basic, Fundamental, Essential",
    "Batty, Crazy, Eccentric",
    "Beatific, Blissful, Serene",
    "Beauteous, Beautiful, Lovely",
    "Beautiful, Attractive, Gorgeous",
    "Becoming, Appropriate, Suitable",
    "Bedazzled, Enchanted, Captivated",
    "Befitting, Suitable, Appropriate",
    "Beguiling, Charming, Enchanting",
    "Belated, Late, Delayed",
    "Belittling, Disparaging, Demeaning",
    "Belligerent, Hostile, Aggressive",
    "Beloved, Cherished, Adored",
    "Beneficent, Kind, Charitable",
    "Beneficial, Helpful, Advantageous",
    "Benevolent, Kind, Charitable",
    "Benign, Gentle, Kind",
    "Berserk, Frenzied, Crazed",
    "Bewitching, Enchanting, Captivating",
    "Biased, Prejudiced, Partial",
    "Biblical, Scriptural, Religious",
    "Bifurcated, Divided, Split",
    "Bigoted, Intolerant, Prejudiced",
    "Bilious, Irritable, Bad-tempered",
    "Binary, Dual, Two-part",
    "Binding, Obligatory, Mandatory",
    "Bipartisan, Cooperative, Collaborative",
    "Bizarre, Strange, Weird",
    "Blabby, Talkative, Gossipy",
    "Blameless, Innocent, Guiltless",
    "Bland, Dull, Insipid",
    "Blasphemous, Sacrilegious, Profane",
    "Blatant, Obvious, Flagrant",
    "Blazing, Burning, Fiery",
    "Bleak, Grim, Dismal",
    "Blessed, Fortunate, Favored",
    "Blissful, Happy, Joyful",
    "Bloated, Swollen, Inflated",
    "Blockish, Stupid, Dull",
    "Blunt, Direct, Straightforward",
    "Boastful, Bragging, Vainglorious",
    "Bodacious, Remarkable, Audacious",
    "Bogus, Fake, Counterfeit",
    "Boisterous, Rowdy, Noisy",
    "Bold, Brave, Fearless",
    "Bombastic, Pompous, Grandiose",
    "Bonny, Attractive, Pretty",
    "Bookish, Scholarly, Academic",
    "Boorish, Rude, Uncouth",
    "Bootless, Useless, Futile",
    "Boring, Dull, Tedious",
    "Bossy, Domineering, Overbearing",
    "Boundless, Limitless, Infinite",
    "Bountiful, Generous, Abundant",
    "Boyish, Youthful, Immature",
    "Brainy, Intelligent, Clever",
    "Brash, Rude, Tactless",
    "Brave, Courageous, Fearless",
    "Brazen, Bold, Shameless",
    "Breathtaking, Astonishing, Spectacular",
    "Breezy, Casual, Relaxed",
    "Brevity, Conciseness, Shortness",
    "Brilliant, Intelligent, Bright",
    "Brisk, Quick, Energetic",
    "Brittle, Fragile, Easily broken",
    "Brooding, Thoughtful, Contemplative",
    "Brotherly, Fraternal, Affectionate",
    "Brutal, Cruel, Savage",
    "Bubbly, Effervescent, Vivacious",
    "Bucolic, Rural, Pastoral", 
    "Burdensome, Onerous, Troublesome",
    "Bureaucratic, Administrative, Official",
    "Burly, Sturdy, Robust",
    "Burnished, Polished, Lustrous",
    "Businesslike, Efficient, Professional",
    "Bustling, Busy, Active",
    "Busy, Occupied, Engaged",
    "Buttery, Smooth, Creamy",
    "Buzzing, Humming, Vibrating",
    "Bygone, Past, Former",
    "Byzantine, Complex, Intricate"
]
 
def check_duplicates():
    print("\nChecking for duplicates in character_names...")
    name_counts = {}
    for name in character_names:
        if name in name_counts:
            name_counts[name] += 1
        else:
            name_counts[name] = 1
    duplicates = [name for name, count in name_counts.items() if count > 1]
    if duplicates:
        print(f"Found duplicate names: {duplicates}")
    else:
        print("No duplicate names found!")
    print(f"Total unique names: {len(set(character_names))}")

    print("\nChecking for duplicates in character_traits...")
    trait_counts = {}
    for trait in character_traits:
        if trait in trait_counts:
            trait_counts[trait] += 1
        else:
            trait_counts[trait] = 1
    duplicates = [trait for trait, count in trait_counts.items() if count > 1]
    if duplicates:
        print(f"Found duplicate traits: {duplicates}")
    else:
        print("No duplicate traits found!")
    print(f"Total unique traits: {len(set(character_traits))}")

# Automatically check for duplicates when the file is used
check_duplicates()