# Weights & Biases settings
wandb_project: null  # Set to your project name
wandb_entity: null   # Set to your username or organization

# Directory settings
model_dir: "orpo_lora_adapters"  # Directory where models and metrics are saved
output_dir: "plots"              # Directory where plots will be saved
metrics_path: null               # Optional: Specific path to a metrics CSV file

# Plot settings
figure_width: 12
figure_height: 8
style: "whitegrid"  # Options: darkgrid, whitegrid, dark, white, ticks
dpi: 300 